//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSoftEntegrasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adisyonlar
    {
        public int ID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Odeme { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Durum { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public string GelenBilgi { get; set; }
        public string SiparisID { get; set; }
        public string SiparisToplam { get; set; }
        public string AraToplam { get; set; }
        public string KDV { get; set; }
        public string SiparisNot { get; set; }
        public string DurumID { get; set; }
        public Nullable<bool> Kabul { get; set; }
        public Nullable<bool> Ret { get; set; }
        public Nullable<bool> Hazirlaniyor { get; set; }
        public Nullable<bool> Yolda { get; set; }
        public Nullable<bool> Teslim { get; set; }
    }
}
