//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSoftEntegrasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int ID { get; set; }
        public string UrunID { get; set; }
        public string UrunAdı { get; set; }
        public string UrunFiyat { get; set; }
        public string SiparisID { get; set; }
        public string Adet { get; set; }
    }
}
